### ISSUE TITLE
Xiaomi device flashing screen are caused and the screen flashes from time to time

### ISSUE THREAD

**Issue by Mr-TLS** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#10]
Xiaomi device apollo, due to the reason of changing the phone model, the brightness adjustment and the flashing screen are caused and the screen flashes from time to time. Is there a solution?

**Comment by reiryuki** [comment]
No, you can use another dolby module instead

**Comment by Mr-TLS** [comment]
Ok, tried all the dolby modules, this one works best, other dolby modules don't work as well as this one,but thanks anyway for your work.
