### ISSUE TITLE
Question: Safe for LineageOS?

### ISSUE THREAD

**Issue by IngwiePhoenix** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#11]
Hello!

I installed LineageOS 18.1 on my Razer Phone 2 and saw that this module exists. So I am quite convinced this should be compatible basically OOB.

However, LineageOS comes with AudioFX (`org.lineageos.audiofx`) and I can not uninstall it from the settings UI.

Can I still install this module or not?

Thanks and kind regards,
Ingwie

**Comment by reiryuki** [comment]
Give it a try.
Discussion tab is opened now, you can ask any other question there.
