### ISSUE TITLE
Conflicts with MIUI Camera

### ISSUE THREAD

**Issue by jaswinprakash** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#12]
I'm using Redmi k20 pro(Raphaelin), this module conflicts with phone camera (miui camera), when take photos camera got freeze
for 2-5 seconds and closes itself or freeze 2-3 seconds and resume app..(Note - no issues with gcam mods)

https://user-images.githubusercontent.com/103166116/167078354-3833ec15-1c3b-4152-87d7-34d89f5cd1c8.mp4

**Comment by reiryuki** [comment]
Maybe you have not read descriptions yet
It changes ro.product... system properties. May breaks some platform apps and features.
