### ISSUE TITLE
Dolby Atmos no longer works every time I restart my phone

### ISSUE THREAD

**Issue by DavidRLTG** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#13]
**Device: M2012K11AG (Poco F3), Operating System: Android 12L crDroid (Modified LineageOS)**
Hello there! the title kinda says it all.. every time I reboot my phone I need to reinstall the module. What the heck! Although, weirdly enough, if I go into the Dolby Atmos app after restart, turn it off, then on again, it will work but ONLY INSIDE THE DOLBY ATMOS APP, like the audio will be modified only while I am inside the app.. Please help!

**Comment by reiryuki** [comment]
Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, issues will be closed immediately.

Please read Troubleshootings also
https://t.me/androidryukimodsdiscussions/29836
https://t.me/androidryukimodsdiscussions/2617

-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module X
3) Full logcat X
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.

Will be re-opened after you send the required files.

**Comment by DavidRLTG** [comment]
[magisk_install_log_2022-05-20T07_52_10.log](https://github.com/reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module/files/8736042/magisk_install_log_2022-05-20T07_52_10.log)
[logs-2022-05-20-07-55-41.zip](https://github.com/reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module/files/8736043/logs-2022-05-20-07-55-41.zip)
[z.zip](https://github.com/reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module/files/8736046/z.zip)

**Comment by reiryuki** [comment]
Install AOSP soundfx Remover and AML

**Comment by reiryuki** [comment]
If no issue left then this will be closed

**Comment by DavidRLTG** [comment]
Hello there! I did what you asked and.. the issue continues.. except now, it just stops working after a long while, not necessarily when restarting the phone. Heck! It's pain xd
