### ISSUE TITLE
Licensing and Code Infringement for Dolby - Code of Conduct Github

### ISSUE THREAD

**Issue by Stormproaudio** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#14]
**Dear Developer** 

Please take note this Project goes beyond the **Code of Conduct** in Github and especially work on your project has been analyse and deemed as Infringement of Codes owned by Dolby Corporation. Please read the notice below :

Dolby Atmos is licensed to Dolby corporation the legal entity that have the rights to distribute or integrate Dolby modules solutions for android devices . Porting is illegal ways of moving copying or distributing Dolby without permission. This is againts the law..this infringe also software and deemed as software piracy. Anybody who is copying, moving, integrating Dolby solutions illegally can be charged of infringing intellectual property owned by the rightful company, corporation groups or companies.

**Read Dolby Terms of Use**
https://www.dolby.com/about/legal/dolby-on-terms-of-use

If You are a Developer do Apply for a Licensing To Test and Integrate Dolby into your Applications and apply for licensing via this Official Form
https://professional.dolby.com/licensing/dolby-license-application-form/

**Licensing and Code of Conduct Github**
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

You are advise to stop halt and remove this project and content until you get Licensing approval from Dolby Licensing Laborataries Corporation. At current your MIT License does not cover the Dolby Atmos Codes that was originally for Razer Phone not any other device.

Thank You.

**Comment by reiryuki** [comment]
I don't trust you :) and I don't like you actually.
