### ISSUE TITLE
Can you change the app color to blue?Just like Dolby app of Oneplus.

### ISSUE THREAD

**Issue by AviderMin** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#16]

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations X
2) Magisk install log if it's a Magisk module X
3) Full logcat X
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.
