### ISSUE TITLE
Display Brightness Error and Heating

### ISSUE THREAD

**Issue by MrSome0ne** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#17]
After the module being installed on the Mi 11 lite NE 5G (Lisa). Device is unstable on automatic brightness settings. Always forces the brightness to 20%. And the brightness adjustment became discontinuous. Also while charging occasionally the device started to heat especially on the top display portion. Don't know why a audio codec would destabilize display.

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 4 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module X
3) Full logcat X
4) Zipped Z folder X

If you miss one of them, read https://t.me/androidryukimodsdiscussions/2618 again please. If you don't understand, learning is the best you can do. Thank you.
