### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by Tareqt13** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#2]
Mi a2 user and awaken os tester. 
I had a problem with the front camera after installing Dolby Atmos. Please help. Screen shot bellow.
![Screenshot_20201219-115757_Camera](https://user-images.githubusercontent.com/69507685/102682146-850bd100-41f1-11eb-9711-ea5e45c7fa5b.png)

**Comment by reiryuki** [comment]
its changing product property values, thats why

no fixes

issue closed
