### ISSUE TITLE
Flashed the module, but the app doesn't open

### ISSUE THREAD

**Issue by NikhilDevani** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#3]
I flashed the latest module, app does not open.
It crashes. 
Device - Poco f1
Rom-Msm 5.0
Kernel - Genos 15.1 evo.

Here is the crash log url if it helps:
https://del.dog/yfulihapom

**Comment by reiryuki** [comment]
Reboot twice without reinstaling will solve
It's new version Magisk sepolicy.rule bug

**Comment by NikhilDevani** [comment]
Solved, thank you.

**Comment by thefaizanbashir** [comment]
Tried this but still not opening sir!
