### ISSUE TITLE
The UI doesn't refresh but the settings get applied

### ISSUE THREAD

**Issue by Kronodile** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#4]
Device: Pocophone F1
ROM: Lineage OS 17.1 Official
Kernel: Stock LineageOS Kernel
The UI doesn't refresh but the settings get applied. I have to reopen the app from recents tab. Is this a known issue or am I the only one facing this issue? The app definitely works and there is a huge improvement to the speakers but the UI doesn't refresh for some reason.

**Comment by reiryuki** [comment]
Follow this report guide: https://t.me/audioryukimods/2618
