### ISSUE TITLE
App not opening, it's showing "Dolby Atoms keeps stopping"

### ISSUE THREAD

**Issue by thefaizanbashir** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#5]
Device: Redmi K20 Pro (Raphael)
ROM: Evolution X 5.4
Kernel: F1XY v0.26
First of all thanks for your hardworking efforts, I'm not criticising your hardwork. I'm just reporting an issue so that you can make it more fantastic in future.
Issue: Whenever i open the app, it's not opening & showing"Dolby Atmos keeps stopping" , i tried rebooting my phone twice still same issue!
Here is the crash log https://del.dog/evinguxygn

**Comment by reiryuki** [comment]
https://github.com/reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module/issues/3

**Comment by thefaizanbashir** [comment]
So i got it working by a trick!
I first set SeLinux to permissive using your given command through Terminal Emulator, IT WORKED! Then i changed it back to Enforcing through SeLinux Mode Changer App. Now it's working fine even with SeLinux Enforcing! Thanks!

**Comment by thefaizanbashir** [comment]
You can post this comment so that if anyone faces the same issue! He can use this trick!

**Comment by reiryuki** [comment]
No problem
Should foolow this: https://t.me/audioryukimods/2618
