### ISSUE TITLE
Brightness Issues

### ISSUE THREAD

**Issue by thefaizanbashir** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#6]
Hey, man! Thanks for your work! I really appreciate your hardwork! I'm not criticizing you! I'm just reporting bugs so that you can make it more stable! 
I tested this mod for 5 days, but there are some major bugs like brightness issues (abnormal brightness issues)! Please try to fix it in your next build, if possible!

**Comment by reiryuki** [comment]
https://t.me/audioryukimods/2617

**Comment by thefaizanbashir** [comment]
Thanks
