### ISSUE TITLE
AAC codec is not supporting for bluetooth headphones

### ISSUE THREAD

**Issue by DeejaySKL** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#7]
After flashing the module an AAC supported headphone is not showing the AAC option after pairing.
Tried uninstalling the module from magisk then again paired the headphone, now it's showing the AAC option.
Also if the headphone is already paired with phone and then I install the module, the AAC option is persist but if I unpair and repair then again no AAC support.

Magisk version: 22.0
Device: Poco F1 (beryllium)
Rom: xiaomi.eu 12.0.3.0
Android 10

Please let me know if any other info needed.

**Comment by reiryuki** [comment]
Please follow this https://t.me/audioryukimods/2618
Otherwise it will be closed
