### ISSUE TITLE
Bass Enhancer not work

### ISSUE THREAD

**Issue by Im-joker** [reiryuki/Dolby-Atmos-Razer-Phone-2-Magisk-Module#8]
Bass Enhancer does not work on Razer Phone 1.

**Comment by reiryuki** [comment]
Optional
https://t.me/audioryukimods/2616
Troubleshootings
https://t.me/audioryukimods/2617
Bug Report
https://t.me/audioryukimods/2618
If you don't do above, it will be closed immediately
